=== unicode-org/conformance/schema/message_fmt2/testgen_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MessageFormat2 data-driven tests source",
  "description": "This documents the format of message_fmt2 source test data before test generation.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "scenario",
    "tests"
  ],
  "properties": {
    "scenario": {
      "type": "string",
      "description": "Identifier for the tests in the file"
    },
    "description": {
      "type": "string",
      "description": "Information about the test scenario."
    },
    "defaultTestProperties": {
      "$ref": "#/$defs/defaultTestProperties"
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/test"
      },
      "minItems": 1
    }
  },
  "$defs": {
    "defaultTestProperties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "testSubtype": {
          "$ref": "#/$defs/testSubtype"
        },
        "locale": {
          "$ref": "#/$defs/locale"
        },
        "pattern": {
          "$ref": "#/$defs/pattern"
        },
        "args": {
          "$ref": "#/$defs/args"
        },
        "verify": {
          "$ref": "#/$defs/verify"
        }
      }
    },
    "test": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "description": {
          "$ref": "#/$defs/description"
        },
        "testSubtype": {
          "$ref": "#/$defs/testSubtype"
        },
        "locale": {
          "$ref": "#/$defs/locale"
        },
        "pattern": {
          "$ref": "#/$defs/pattern"
        },
        "args": {
          "$ref": "#/$defs/args"
        },
        "verify": {
          "$ref": "#/$defs/verify"
        }
      }
    },
    "description": {
      "type": "string",
      "description": "Information about the test."
    },
    "testSubtype": {
      "description": "A tag for the executor to decide how to run the test.",
      "enum": [
        "syntax",
        "selector",
        "formatter"
      ]
    },
    "locale": {
      "type": "string"
    },
    "pattern": {
      "type": "string"
    },
    "args": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/arg"
      }
    },
    "arg": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "argType",
        "value"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "argType": {
          "enum": [
            "string",
            "number",
            "datetime"
          ]
        },
        "value": {}
      },
      "anyOf": [
        {
          "properties": {
            "argType": {
              "const": "string"
            },
            "value": {
              "type": "string"
            }
          }
        },
        {
          "properties": {
            "argType": {
              "const": "datetime"
            },
            "value": {
              "type": "string"
            }
          }
        },
        {
          "properties": {
            "argType": {
              "const": "number"
            },
            "value": {
              "type": "number"
            }
          }
        }
      ]
    },
    "verify": {
      "type": "string"
    }
  }
}

=== unicode-org/conformance/testgen/icu75/message_fmt2/syntax/local.json
{
  "scenario": "Local syntax",
  "description": "Placeholders defined in the pattern",
  "defaultTestProperties": {
    "testSubtype": "syntax",
    "locale": "en-US"
  },
  "tests": [
    {
      "description": "Includes locals with unquoted literal values",
      "pattern": ".local $foo = {bar} {{bar {$foo}}}",
      "verify": "bar bar"
    },
    {
      "description": "Includes locals with quoted literal values",
      "pattern": ".local $foo = {|bar|} {{bar {$foo}}}",
      "verify": "bar bar"
    },
    {
      "description": "Overrides input values with local values",
      "pattern": ".local $foo = {bar} {{bar {$foo}}}",
      "args": [
        {
          "argType": "string",
          "name": "foo",
          "value": "foo"
        }
      ],
      "verify": "bar bar"
    },
    {
      "description": "Allows local values to reference input values",
      "pattern": ".local $foo = {$baz} .local $bar = {$foo} {{bar {$bar}}}",
      "args": [
        {
          "argType": "string",
          "name": "baz",
          "value": "foo"
        }
      ],
      "verify": "bar foo"
    },
    {
      "description": "Allows local values to reference other local values",
      "pattern": ".local $x = {42} .local $y = {$x} {{{$x} {$y}}}",
      "verify": "42 42"
    },
    {
      "description": "Allows local values to reference other local values that reference input values",
      "pattern": ".local $foo = {$baz} .local $bar = {$foo} {{bar {$bar}}}",
      "args": [
        {
          "argType": "string",
          "name": "baz",
          "value": "foo"
        }
      ],
      "verify": "bar foo"
    }
  ]
}

=== unicode-org/conformance/testgen/icu75/message_fmt2/syntax/input.json
{
  "scenario": "Input syntax",
  "description": "Syntax to describe expected args",
  "defaultTestProperties": {
    "testSubtype": "syntax",
    "locale": "en-US"
  },
  "tests": [
    {
      "description": "Includes input values in the output",
      "pattern": ".input {$foo} {{bar {$foo}}}",
      "args": [
        {
          "argType": "string",
          "name": "foo",
          "value": "foo"
        }
      ],
      "verify": "bar foo"
    },
    {
      "description": "Allows inputs as local placeholder values",
      "pattern": ".input {$foo} .local $bar = {$foo} {{bar {$bar}}}",
      "args": [
        {
          "argType": "string",
          "name": "foo",
          "value": "foo"
        }
      ],
      "verify": "bar foo"
    }
  ]
}

=== unicode-org/conformance/testgen/icu75/message_fmt2/syntax/literal.json
{
  "scenario": "Literal syntax",
  "description": "Literal content placed directly into the pattern",
  "defaultTestProperties": {
    "testSubtype": "syntax"
  },
  "tests": [
    {
      "description": "Includes basic literals",
      "locale": "en-US",
      "pattern": "hello world",
      "verify": "hello world"
    },
    {
      "description": "Includes unquoted literals",
      "locale": "en-US",
      "pattern": "hello {world}",
      "verify": "hello world"
    },
    {
      "description": "Includes quoted literals",
      "locale": "en-US",
      "pattern": "hello {|world|}",
      "verify": "hello world"
    },
    {
      "description": "Allows empty quoted literals",
      "locale": "en-US",
      "pattern": "hello {||}",
      "verify": "hello "
    }
  ]
}

=== unicode-org/conformance/testgen/icu75/message_fmt2/syntax/literal-text.json
{
  "scenario": "Literal text",
  "description": "Text placed directly into the pattern",
  "defaultTestProperties": {
    "testSubtype": "syntax"
  },
  "tests": [
    {
      "description": "Includes basic literals",
      "locale": "en-US",
      "pattern": "hello world",
      "verify": "hello world"
    },
    {
      "description": "Includes unquoted literals",
      "locale": "en-US",
      "pattern": "hello {world}",
      "verify": "hello world"
    }
  ]
}

=== unicode-org/conformance/testgen/icu75/message_fmt2/syntax/escapes.json
{
  "scenario": "Escapes",
  "description": "Handling of escaped characters",
  "defaultTestProperties": {
    "testSubtype": "syntax",
    "locale": "en-US"
  },
  "tests": [
    {
      "description": "Ignores character escapes",
      "pattern": "h\nel\rl\to",
      "verify": "hello"
    },
    {
      "description": "Ignores unicode escapes",
      "pattern": "hell\u3000o",
      "verify": "hello"
    }
  ]
}

=== unicode-org/conformance/testgen/icu75/message_fmt2/syntax/whitespace.json
{
  "scenario": "Whitespace",
  "description": "Leading and trailing space characters",
  "defaultTestProperties": {
    "testSubtype": "syntax"
  },
  "tests": [
    {
      "description": "Preserves leading space on basic literals",
      "locale": "en-US",
      "pattern": "  hello world",
      "verify": "  hello world"
    },
    {
      "description": "Removes leading space on unquoted literals",
      "locale": "en-US",
      "pattern": "hello {  world}",
      "verify": "hello world"
    },
    {
      "description": "Preserves trailing space on basic literals",
      "locale": "en-US",
      "pattern": "hello world  ",
      "verify": "hello world  "
    },
    {
      "description": "Removes trailing space on unquoted literals",
      "locale": "en-US",
      "pattern": "hello {world  }",
      "verify": "hello world"
    }
  ]
}
